
### user login
GET http://localhost:3000/auth/users/login?email=davier@gmail.com&password=12345


### register user
POST http://localhost:3000/auth/users/register?organizationId=1 HTTP/1.1
Content-Type: application/json

{
  "name": "manuela",
  "lastName": "diaz",
  "email": "manuela@gmail.com",
  "phone": "31099292",
  "password": "12345",
  "role": "user"
}

### delete use by id
DELETE http://localhost:3000/auth/users/1